spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionArticle
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swaggerui
